name: master CI, CD workflow 
on: 
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master"]
jobs:
  master_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: CI
        run: npm ci
      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
